

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    depends_on:
      - database

  database:
    image: postgres:13
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
