volumes:
  postgres_data:  # Define the named volume
    name: flask-volume  # Optionally, set a custom name for the volume

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.api-key
      - .env.dockersecrets
    depends_on:
      - database

  database:
    image: postgres:13
    env_file:
    - .env.dockersecrets
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Use the volume defined above
